### ISSUE TITLE
GUI glitches

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [FFDA/SourCherry#1]
After opening a database, this happens:

https://youtube.com/shorts/6Dt1mkbFjos?feature=share

https://youtube.com/shorts/NwSTuW7ilLk?feature=share

I'm using sourcherry alpha 2 on Android 9, moto e6 plus

**Comment by FFDA** [comment]
Hi,

I tried to reproduce this glitch on three phones: Redmi 9 Pro (Android 11), Samsung S7 (Android 8), Samsung S9 (Android 9) and on one virtual device that I tried to make as close to Moto E6 Plus as possible and I couldn't.

In the video it doesn't look that you are using database with personal information. Would you will be willing to share the file?
There is a chance that a file has some data that make the app to glitch out. However, if I won't be able to reproduce the glitch I don't think I will be able to solve it.

**Comment by ItsIgnacioPortal** [comment]
It seems that the trigger for this bug is you have to go to the [Android developer settings](https://developer.android.com/studio/debug/dev-options) and set "Night Mode" to "Always On"

Also thanks for responding so quickly. It's nice seeing developers who care about their projects

**Comment by FFDA** [comment]
I still can't reproduce the glitch.

Android 11 uses dark theme without an issue when phone goes to night mode automatically and turning dark mode in developer settings have no effect neither.
I couldn't find "Night mode" in other two phone anywhere. Even in developer options, but I tried your database and it works on my phone too.
The only reason why I thought that might have something to do with it is because I have one node in my main database that I can not open with CherryTree I have currently installed on my laptop ( version 0.38.2). It simply crashes the program. That node was created with newer version (newest right now is 0.99.47) of Cherrytree.

Does your phone have a dark mode that you can turn on not in developer settings? There might be a reason why it is only there.

It's a bit late here so I will try to look into it a bit more tomorrow. However, I would like to test if apps "native" dark mode works on your phone. If you can't turn it on not in developer settings I think I cant compile an apk only with it. Would you be willing to install it and test it?

> Also thanks for responding so quickly. It's nice seeing developers who care about their projects

I will tell you a secret. It's easy when you have just one issue on github and some free time.

**Comment by FFDA** [comment]
I finally managed to reproduce the bug in emulator on Android 8 and 9 while working for Night Mode only apk. However, I couldn't reproduce it on physical device, yet. Not that it matters...

It definitely caused by Night mode. But I can't find out what's the reason for that yet. Or what element of the UI actually causing it.

**Comment by ItsIgnacioPortal** [comment]
I installed that apk; the bug is gone. Good job 😁
