### ISSUE TITLE
Suggestion: Open file directly

### ISSUE THREAD

**Issue by metal450** [FFDA/SourCherry#10]
With many apps, they "associate" a filetype, so you can navigate to the file directly, tap it, & it will prompt you to open it in the app.  Would be cool if the same were possible with .ctb.

**Comment by FFDA** [comment]
Try this [apk](https://github.com/FFDA/ffda.github.storage/raw/main/SourCherry-releases/SourCherry_beta-2-intent-filters.apk).

I tried to open files through Total Commander, Google Files, Signal (messaging app), Simple File Manager. It works with those apps, but to make it work with last two took some tinkering. It seems that way uri might have other limitations, but not always...

Please, test with as many different apps that you expect to receive databases from and with as many different type of databases as you can. Report any crashes and messages you see here.

I changed how preferences are stored. **Clear data after installing new apk**, otherwise app might crash on startup.

**Comment by FFDA** [comment]
I’ll assume that no response means that everything works as expected. Closing this issue.

**Comment by metal450** [comment]
Hi; been traveling for 2 weeks and haven't been app-testing for a bit.

I just gave this a try (with the latest 1.0.0 build). The behavior seems to be the same.  If I tap a .ctb file in my file manager, Android doesn't recognize which app to open it with (as with other file formats).  Tried 2 file managers: "My Files" (Samsung's default on all their devices), and "FX File Manager" (the 3rd party one I use).

For instance, if I tap an .mp3 file in either file manager, it offers to open it in any of my installed music players; if I tap an html file, it offers to open it in any of the installed browsers. But if I tap a ctb file, it doesn't know what to do.  My Files, for example, says "You don't have any apps that can open this type of file. You can search for one in the Play Store."
