### ISSUE TITLE
"Mirror" Directory For Syncing

### ISSUE THREAD

**Issue by metal450** [FFDA/SourCherry#13]
This is another follow up to: https://github.com/FFDA/SourCherry/issues/12

As required by Android, SourCherry stores its db in either /data/data/lt.ffda.sourcherry/files or /Android/data/lt.ffda.sourcherry/files. Prior to Android 11, the former required root but the latter did not. Apparently as of Android 11, now both locations require root (sigh).  This means that only rooted devices can sync dbs with solutions like SyncThing (and even so, the user must still manually set the owner/group of the db after each sync, as otherwise it will be owned by "root" & unreadable by SourCherry). Needless to say this is less than ideal, but seemed unavoidable thanks to Google's overly aggressive access limitations.

However, I realized that another app I use has a great solution. NeutriNote (https://play.google.com/store/apps/details?id=com.appmindlab.nano), like all apps, stores its data in app-scoped storage - but it has a "mirror" option, where you point it to a path of your choosing. It then "monitors" that directory, and whenever the data there changes, auto-imports into its own internal storage; and whenever the app makes edits, it auto-exports it there. Then you can point SyncThing to that "mirror" folder and voila: you have two-way syncing without any need for root or changing owners/groups, etc.

As SourCherry is currently read-only, it seems like this would be even easier: only the inbound/import direction needs to be handled.

Think something like that might be possible? Just a setting so that whenever the app is launched, it checks a user-selected path for a newer db & just transparently copies it over - enabling fully automated syncing?

**Comment by FFDA** [comment]
Hi,

It should be possible to do. Because app can read/write any file that user gives access to. It just some kind of abstraction that is not enough for android's sqlite implementation. If that abstraction shows modification datetime (I just checked – it does) then that's quite easy (I hope). However, the problem is, I don't have any time to work on the app (as can be seen in commit history). Last time I had some time it was early September and I spent it on making qBittorrent-Controller work on Android 12. I think that app was complete abandoned by the dev.

Next time I'll have some time I will spend on properly documenting both readers. There are places that might be hard for others to understand how they work.

**Comment by metal450** [comment]
>I don't have any time to work on the app

Fair enough - maybe just consider it an idea for if/when you do come back to this then, or for if you yourself find the need to sync on a non-rooted phone. Seemed like a good solution that works well in that other app :)

**Comment by FFDA** [comment]
Hello,

I had some time and tried to do "Mirror Database" function. I did some testing and everything works, but my testing was manual, because I don't use "SyncThing", or anything else (I simply get a new DB from cloud storage when I need it).

You can download apk for testing from [here.](https://github.com/FFDA/ffda.github.storage/raw/main/SourCherry-releases/SourCherry_1.1.0-MirrorDatabase.apk)

While I was working on this feature I made some notes and I will copy them here. It just some thought what might be useful to know for the user and what to expect:

**Comment by FFDA** [comment]
Hello,

I had some time and worked on this issue. I did some testing and it works, but my testing was manual, because I do not use SyncThing or any other app. I simply import new DB from the cloud when I need it.

You can download new app from [here](https://github.com/FFDA/ffda.github.storage/raw/main/SourCherry-releases/SourCherry_1.1.0-MirrorDatabase.apk). 

I kept some notes while I was working on this feature and will post then bellow. They are just things that I thought user might need to know about how this feature works and what to expect:

- You have to select Database Mirror Folder and Database Mirror File. The later is needed to get the filename of the Mirror Database file that will be searched for in Database Mirror Folder.
- Selecting Database Mirror Folder is necessary, because permissions for the file is not enough. If any other program touches or changes the file, permissions for other apps might be revoked. As if, let's say, user copies over the file with the same filename in the same folder and overwrites the file that app has permission to read.
- Changes (last modified date) will be tracked AFTER you set Mirror Database Folder and Mirror Database File even if Mirror Database File already differs when you setting up Mirror Database those changes won't trigger importation of the database.
- If Mirror Database type (SQL/XML) differs from the one that is set to open. App still overwrite the database, however when opening it should crash and depending on if “Open this database on startup” checkbox is checked it might lead to boot loop.
- Not password protected XML databases are NOT supported. They can be opened in place so in theory this function is not needed for them. However, I think (haven't tested it) if any program overwrites the database/file app will loose any permissions that were granted before hand.
- If “Restore last node on startup” is on and node that should be opened is missing (deleted on the mirror database file) - app should fail safely and do not load any node, just open the database. If it does not work this way - please report.
- Every time user changes or opens a different database from MainActivity Mirror Database settings are turned off/removed.

**Comment by metal450** [comment]
Confirmed, it works perfect w/ SyncThing!  Thanks for doing this 👍 💯
