### ISSUE TITLE
Omit marked to exclude checkbox default

### ISSUE THREAD

**Issue by metal450** [FFDA/SourCherry#15]
A couple suggestions:

* Each time the app is launched, it forgets the previous setting for "Omit marked to exclude." It would be great if it remembered it - or at least defaulted to "checked," as typically if a node is marked to exclude from searches, we would want it to be excluded.
* Also, checking/unchecking this checkbox clears any typed text.

The issue: I keep finding myself doing a search, realizing that it's including all of my "trash" nodes again, re-checking the checkbox, then it erases what I've typed so I have to retype it again.

Thanks!

**Comment by FFDA** [comment]
I actually planed to release 1.3.0-beta as a normal version tomorrow. So I will delay it a bit and add these requested features to that release.

> Also, checking/unchecking this checkbox clears any typed text.

Just fixed this. I actually did it on purpose, because previously after checking that checkbox user would have had to type (or delete) a symbol for it to have any effect.

> app is launched, it forgets the previous setting for "Omit marked to exclude."

I'll make it to remember the choice. At least in my twisted mind it should be off by default.

**Comment by metal450** [comment]
Great, thanks!

> I actually did it on purpose, because previously after checking that checkbox user would have had to type (or delete) a symbol for it to have any effect.

Or could just make the check/uncheck action raise an event to trigger a new search?

**Comment by FFDA** [comment]
> Or could just make the check/uncheck action raise an event to trigger a new search?
That's what I did.

I just released new version on Play Store and on GitHub. It includes both changes to FilterNodes function.

**Comment by metal450** [comment]
Great, it works - thanks!!
