### ISSUE TITLE
Doesn't Save

### ISSUE THREAD

**Issue by johnnyjmcivorv** [FFDA/SourCherry#24]
I'm on Android, Google Pixel 8A. I open a .ctb file and it renders correctly. However, the save button does not work, and neither does exiting edit mode and clicking "save" on the dialog box. I think it _tries_ to save, but when you actually open the file again there is no change to the document.

**Comment by FFDA** [comment]
Hello,

It will be hard to replicate the bug with the information you provided. I’ll definitely need to know the Android version as well.

Do the changes fail to persist for only one node, or for all of them? If it’s just one node, does it have any large files attached to it? Perhaps images or LaTeX?

Could you try opening a database from [here](https://github.com/FFDA/ffda.github.storage/tree/main/test_databases) on your phone? Are you experiencing the same bug with it?

Could you elaborate on this part: `I think it tries to save, but when you actually open the file again, there is no change to the document.` What do you mean by `open the file again`? Do you open the app, tap the `Single File` button, and then select the database file? If so, all the changes will disappear because the version with changes will be overwritten if the database filenames match. You need to tap the `Open` button to load the last used database.

**Comment by johnnyjmcivorv** [comment]
Pixel 8 Pro

Android 14

Android Security Update: September 5, 2024

Google Play System Update: October 1, 2024

Baseband Version: g5300i-240308-240611-B-11952068,g5300i-240308-240611-B-11952068

Kernel: 5.15.137-android14-11-gbc062a78e195-ab12057991
#1 Mon Jul 8 12:34:46 UTC 2024

Build Number: AP2A.240905.003.B1

------------------------------------------------------------------------------

None of the nodes save. There is an image attached in one of the nodes, but that's not the node I was trying to save.

The save button is unresponsive and does not give an indication that it saved. It doesn't save, even when I click save on the dialog box that says I have unsaved changes.

By open the file again, I mean that after I click save and open it up on my desktop, or re-open it with the app, there are no changes. In other words, it didn't actually save.

**Comment by FFDA** [comment]
I will close this issue at some point in the feature if you will not confirm that you actually looking for changes in the correct copy of the database.
